### PR TITLE
fix(tables): SSR crash from tableKeys in a 'use client' module + drop redundant flushChunks

### PR DESCRIPTION
**Pull request by waleedlatif1**
## Summary
Two fixes, both off `staging`:

### 1. Tables list crash at SSR (regression from #5196)
The tables list page failed to load in staging with:
```
TypeError: i.tableKeys.list is not a function
  (In 'i.tableKeys.list(b, "active")', 'i.tableKeys.list' is undefined)
  at .next/server/chunks/ssr/[root-of-the-server]
```
**Cause:** `tables/prefetch.ts` is a server component, but it imported `tableKeys` from `hooks/queries/tables.ts`, which carries `'use client'`. When a server module imports from a `'use client'` module, Next.js replaces the export with a **client-reference stub** in the server bundle — so `tableKeys.list` is `undefined` at SSR. (The other three prefetch pages were fine because their key factories live in non-`'use client'` modules, e.g. `folder-keys.ts`.)

**Fix:** Extract the key factory into `hooks/queries/utils/table-keys.ts` (no `'use client'`), mirroring the existing `folder-keys.ts` pattern, and import it from there in the prefetch, the hook, the table trigger/poller, and the two consumers. `tables.ts` now imports the factory instead of defining it.

### 2. Redundant `flushChunks()` on the SSE error path (`chat.tsx`)
Addresses a Greptile P2 from the release PR. On an error `final` event the reader stops (`return true`), so the post-loop flush is the single flush point. Defer the error append to after that flush — single flush, correct ordering — instead of flushing inside `onEvent` and again post-loop. No behavior change.

## Type of Change
- [x] Bug fix (SSR crash) + minor refactor

## Testing
- `prefetch.test.ts` (9 tests) green; `tsc` 0 errors; Biome clean; `check:react-query` passes.
- The SSR fix mirrors the proven `folder-keys.ts` pattern (pure non-`'use client'` module); CI's "Test and Build" exercises the real `next build`/SSR path.

## Checklist
- [x] Code follows project style guidelines
- [x] Self-reviewed my changes
- [x] Tests added/updated and passing
- [x] No new warnings introduced
- [x] I confirm that I have read and agree to the terms outlined in the [Contributor License Agreement (CLA)](./CONTRIBUTING.md#contributor-license-agreement-cla)

### CODE REVIEW

**Comment by waleedlatif1** [comment]
@greptile review

**Comment by waleedlatif1** [comment]
@cursor review
